name: Build and push cpu docker image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push cpu image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/cpu.Dockerfile
          push: true
          tags: shashankbansal56/nondefaced-detector:latest-cpu
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
